export type Area={id:string;name:string;color:string|null;description?:string|null};
export type Project={id:string;name:string;description:string|null;areaId:string;status:string;priority:string;maturity:string;projectType:string;nextAction?:string|null;targetDate?:string|Date|null;progressPercentage:number;isFrozen?:boolean;frozenReason?:string|null;frozenUntil?:string|Date|null;updatedAt:string|Date|null;createdAt?:string|Date|null};
export type Task={id:string;title:string;description?:string|null;projectId?:string|null;areaId?:string|null;status:string;priority:string;dueDate?:string|Date|null;isToday?:boolean;isCritical?:boolean;context?:string;completedAt?:string|Date|null;createdAt?:string|Date|null;updatedAt?:string|Date|null};
export type Asset={id:string;name:string;projectId?:string|null;areaId?:string|null;type:string;provider?:string|null;url?:string|null;accountEmail?:string|null;passwordManagerReference?:string|null;renewalDate?:string|Date|null;status:string;cost?:number|null;currency?:string|null;createdAt?:string|Date|null;updatedAt?:string|Date|null;notes?:string|null};
export type Idea={id:string;title:string;description?:string|null;areaId?:string|null;projectId?:string|null;potential:string|null;complexity:string|null;status:string;reviewDate?:string|Date|null;createdAt?:string|Date|null;updatedAt?:string|Date|null;notes?:string|null};
export type Due={id:string;title:string;description?:string|null;projectId?:string|null;assetId?:string|null;type:string;dueDate:string|Date;reminderDate?:string|Date|null;recurrence?:string;amount?:number|null;currency?:string|null;status:string;createdAt?:string|Date|null;updatedAt?:string|Date|null};
export type Review={id:string;title:string;description?:string|null;projectId?:string|null;areaId?:string|null;type:string;frequency:string;nextReviewDate:string|Date;lastReviewDate?:string|Date|null;status:string;createdAt?:string|Date|null;updatedAt?:string|Date|null};
const iso=(n:number)=>new Date(Date.now()+n*86400000).toISOString();
export const initialData={
 areas:[{id:"a1",name:"Abundia",color:"#1e293b"},{id:"a2",name:"Apps personales",color:"#2563eb"},{id:"a3",name:"Webs",color:"#64748b"},{id:"a4",name:"Ecommerce",color:"#059669"},{id:"a5",name:"Newsletter",color:"#7c3aed"},{id:"a6",name:"Infraestructura",color:"#d97706"},{id:"a7",name:"Administración",color:"#475569"}] as Area[],
 projects:[
  {id:"p1",name:"Abundia Agenda",description:"Centro operativo de turnos para clientes de Abundia.",areaId:"a1",status:"active",priority:"critical",maturity:"development",projectType:"app",nextAction:"Cerrar alcance funcional del MVP",targetDate:iso(30),progressPercentage:62,updatedAt:iso(-1)},
  {id:"p2",name:"Portal Abundia",description:"Portal comercial y de suscripciones.",areaId:"a1",status:"blocked",priority:"high",maturity:"testing",projectType:"web",progressPercentage:74,updatedAt:iso(-8)},
  {id:"p3",name:"Landing Abundia",description:"Sitio principal de adquisición.",areaId:"a1",status:"active",priority:"medium",maturity:"production",projectType:"web",nextAction:"Revisar conversión del hero",progressPercentage:85,updatedAt:iso(-3)},
  {id:"p4",name:"Ticketera Abundia",description:"Gestión de soporte.",areaId:"a1",status:"paused",priority:"low",maturity:"design",projectType:"app",progressPercentage:20,updatedAt:iso(-20)},
  {id:"p5",name:"Sistema de pagos Abundia",description:"Flujos de cobro y suscripciones.",areaId:"a1",status:"active",priority:"high",maturity:"validation",projectType:"business",nextAction:"Validar flujo de suscripción",progressPercentage:42,updatedAt:iso(-4)},
  {id:"p6",name:"App de inversiones",description:"Tablero personal de cartera.",areaId:"a2",status:"frozen",priority:"low",maturity:"design",projectType:"app",progressPercentage:18,isFrozen:true,frozenReason:"Reducir frentes abiertos",frozenUntil:iso(45),updatedAt:iso(-24)},
  {id:"p7",name:"App peluquería",description:"Gestión integral del negocio.",areaId:"a2",status:"active",priority:"medium",maturity:"production",projectType:"app",nextAction:"Probar cierre de caja",progressPercentage:78,updatedAt:iso(-2)},
  {id:"p8",name:"App gestión de proyectos",description:"Este centro de control personal.",areaId:"a2",status:"active",priority:"critical",maturity:"development",projectType:"app",nextAction:"Completar navegación del MVP",progressPercentage:48,updatedAt:iso(0)},
  {id:"p9",name:"Ecommerce productos capilares",description:"Tienda de productos profesionales.",areaId:"a4",status:"active",priority:"high",maturity:"testing",projectType:"ecommerce",nextAction:"Cargar catálogo inicial",progressPercentage:56,updatedAt:iso(-2)},
  {id:"p10",name:"Newsletter peluquería",description:"Canal editorial semanal.",areaId:"a5",status:"active",priority:"medium",maturity:"production",projectType:"newsletter",nextAction:"Escribir edición del viernes",progressPercentage:70,updatedAt:iso(-5)},
  {id:"p11",name:"Servidor personal",description:"Infraestructura y backups.",areaId:"a6",status:"blocked",priority:"high",maturity:"maintenance",projectType:"infrastructure",progressPercentage:65,updatedAt:iso(-12)}
 ] as Project[],
 tasks:[{id:"t1",title:"Definir módulos mínimos del MVP",projectId:"p1",status:"in_progress",priority:"critical",dueDate:iso(0),isToday:true,isCritical:true,context:"development"},{id:"t2",title:"Resolver credenciales de staging",projectId:"p2",status:"blocked",priority:"high",dueDate:iso(-2),isCritical:true,context:"admin"},{id:"t3",title:"Revisar catálogo y precios",projectId:"p9",status:"pending",priority:"high",dueDate:iso(2),isToday:true,context:"review"},{id:"t4",title:"Borrador de newsletter",projectId:"p10",status:"pending",priority:"medium",dueDate:iso(4),context:"content"},{id:"t5",title:"Procesar notas sueltas",status:"inbox",priority:"low",isToday:true},{id:"t6",title:"Probar flujo de caja",projectId:"p7",status:"completed",priority:"medium",dueDate:iso(-1),context:"review"}] as Task[],
 assets:[{id:"as1",name:"Dominio abundia.app",projectId:"p1",type:"domain",provider:"Cloudflare",url:"https://abundia.app",accountEmail:"admin@abundia.app",passwordManagerReference:"Bitwarden: Abundia / Dominio",renewalDate:iso(18),status:"active"},{id:"as2",name:"Repositorio Agenda",projectId:"p1",type:"repository",provider:"GitHub",url:"https://github.com/",status:"active"},{id:"as3",name:"Servidor principal",projectId:"p11",type:"server",provider:"Hetzner",passwordManagerReference:"Bitwarden: Infra / Hetzner",renewalDate:iso(9),status:"active"}] as Asset[],
 ideas:[{id:"i1",title:"Biblioteca de decisiones",description:"Registrar por qué se eligió cada camino.",areaId:"a2",potential:"high",complexity:"medium",status:"evaluating",reviewDate:iso(14)},{id:"i2",title:"Radar de costos SaaS",description:"Centralizar costos recurrentes.",areaId:"a7",potential:"medium",complexity:"low",status:"captured",reviewDate:iso(21)}] as Idea[],
 dues:[{id:"d1",title:"Renovar dominio abundia.app",projectId:"p1",type:"domain",dueDate:iso(18),amount:18,currency:"USD",status:"pending"},{id:"d2",title:"Backup del servidor",projectId:"p11",type:"backup",dueDate:iso(-1),status:"pending"},{id:"d3",title:"Licencia de diseño",projectId:"p9",type:"license",dueDate:iso(6),amount:15,currency:"USD",status:"pending"}] as Due[],
 reviews:[{id:"r1",title:"Revisión semanal de foco",type:"weekly_review",frequency:"weekly",nextReviewDate:iso(2),status:"pending"},{id:"r2",title:"Revisión de backups",projectId:"p11",type:"backup_review",frequency:"monthly",nextReviewDate:iso(-3),status:"pending"}] as Review[],
 focus:{mainProjectId:"p1",secondaryProjectIds:["p9","p10"],avoidProjectIds:["p6","p4"],weeklyGoal:"Cerrar el alcance funcional y dejar el MVP listo para validar.",notes:"Proteger dos bloques de trabajo profundo."}
};
