"use client";
import { Archive, Box, FolderKanban, Pencil, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Progress } from "@/components/ui/progress";
import { BoardSection } from "@/components/boards/board-section";
import { TaskSection } from "@/components/tasks/task-section";
import { ResourceSection } from "@/components/resources/resource-section";
import type { ExplorerArea, ExplorerModule, ExplorerProject, ExplorerSelection } from "@/lib/explorer-types";
const placeholders = ["Documentos", "Credenciales", "Decisiones", "Fechas", "Alertas"];
export function ExplorerDetail({ area, project, module: selectedModule, onSelect, onCreate, onEdit, onArchive }: { area?: ExplorerArea; project?: ExplorerProject; module?: ExplorerModule; onSelect: (selection: NonNullable<ExplorerSelection>) => void; onCreate: (kind: "project" | "module") => void; onEdit: () => void; onArchive: () => void }) {
  const node = selectedModule ?? project ?? area; if (!node) return <div className="grid min-h-96 place-items-center text-center text-sm text-slate-500"><div><FolderKanban className="mx-auto mb-3 size-10 text-slate-300" /><p>Seleccioná un área, proyecto o módulo.</p></div></div>;
  const kind = selectedModule ? "Módulo" : project ? "Proyecto" : "Área";
  return <div className="p-5 md:p-7"><div className="flex flex-col gap-4 border-b border-slate-200 pb-5 sm:flex-row sm:items-start sm:justify-between"><div><div className="mb-2 flex items-center gap-2"><Badge variant="outline">{kind}</Badge><Badge className="bg-slate-100 text-slate-700 hover:bg-slate-100">{node.status}</Badge></div><h1 className="text-2xl font-semibold tracking-tight">{node.name}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600">{node.description || "Sin descripción todavía."}</p></div><div className="flex shrink-0 gap-2">{area && !project && <Button onClick={() => onCreate("project")}><Plus className="size-4" />Crear proyecto</Button>}{project && !selectedModule && <Button onClick={() => onCreate("module")}><Plus className="size-4" />Crear módulo</Button>}<Button variant="outline" onClick={onEdit}><Pencil className="size-4" />Editar</Button><Button variant="outline" className="text-red-700" onClick={onArchive}><Archive className="size-4" />Archivar</Button></div></div>
    {(project || selectedModule) && <div className="grid gap-x-8 gap-y-5 border-b border-slate-200 py-6 sm:grid-cols-2"><Info label="Área" value={area?.name} />{selectedModule && <Info label="Proyecto" value={project?.name} />}<Info label="Prioridad" value={(selectedModule ?? project)?.priority} /><Info label="Próxima acción" value={(selectedModule ?? project)?.nextAction || "Sin definir"} />{(selectedModule ?? project)?.blockedReason && <Info label="Motivo de bloqueo" value={(selectedModule ?? project)?.blockedReason} />}<div><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-400">Progreso · {(selectedModule ?? project)?.progressPercentage}%</p><Progress value={(selectedModule ?? project)?.progressPercentage} /></div></div>}
    {area && <TaskSection key={`${area.id}-${project?.id ?? "area"}-${selectedModule?.id ?? "level"}`} areaId={area.id} projectId={project?.id} moduleId={selectedModule?.id} />}
    {area && <ResourceSection key={`resources-${area.id}-${project?.id ?? "area"}-${selectedModule?.id ?? "level"}`} areaId={area.id} projectId={project?.id} moduleId={selectedModule?.id} />}
    {area && <BoardSection key={`boards-${area.id}-${project?.id ?? "area"}-${selectedModule?.id ?? "level"}`} areaId={area.id} projectId={project?.id} moduleId={selectedModule?.id} />}
    {area && !project && <ChildList title={`Proyectos (${area.projects.length})`} items={area.projects} empty="Todavía no hay proyectos en esta área." icon={<FolderKanban className="size-4" />} onClick={(id) => onSelect({ type: "project", id })} />}
    {project && !selectedModule && <ChildList title={`Módulos (${project.modules.length})`} items={project.modules} empty="Este proyecto todavía no tiene módulos." icon={<Box className="size-4" />} onClick={(id) => onSelect({ type: "module", id })} />}
    {selectedModule && <div className="py-6"><h2 className="mb-3 text-sm font-semibold">Secciones del módulo</h2><div className="divide-y divide-slate-200 rounded-lg border border-slate-200">{placeholders.map((item) => <div key={item} className="flex items-center justify-between gap-4 px-4 py-3"><span className="text-sm font-medium">{item}</span><span className="text-xs text-slate-400">{item === "Credenciales" ? "La seguridad sensible será gestionada por La Caja en una próxima integración." : "Se implementará en una próxima iteración."}</span></div>)}</div></div>}
  </div>;
}
function Info({ label, value }: { label: string; value?: string | null }) { return <div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-1 text-sm text-slate-800">{value}</p></div>; }
function ChildList({ title, items, empty, icon, onClick }: { title: string; items: { id: string; name: string; status: string }[]; empty: string; icon: React.ReactNode; onClick: (id: string) => void }) { return <div className="py-6"><h2 className="mb-3 text-sm font-semibold">{title}</h2>{items.length === 0 ? <div className="rounded-lg border border-dashed border-slate-300 px-4 py-7 text-center text-sm text-slate-500">{empty}</div> : <div className="divide-y divide-slate-200 rounded-lg border border-slate-200">{items.map((item) => <button key={item.id} className="flex w-full items-center gap-3 px-4 py-3 text-left hover:bg-slate-50" onClick={() => onClick(item.id)}>{icon}<span className="flex-1 text-sm font-medium">{item.name}</span><span className="text-xs capitalize text-slate-400">{item.status}</span></button>)}</div>}</div>; }
