"use client";
import { useEffect, useState } from "react";
import { Check, Clock3, MoreHorizontal, Pencil, Plus, Trash2 } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { TaskFormModal } from "@/components/tasks/task-form-modal";
import type { ExplorerTask, TaskStatus } from "@/lib/task-types";

const statusLabels: Record<TaskStatus, string> = { inbox: "Inbox", pending: "Pendiente", in_progress: "En progreso", waiting: "En espera", blocked: "Bloqueada", completed: "Completada", discarded: "Descartada" };
const priorityLabels = { critical: "Crítica", high: "Alta", medium: "Media", low: "Baja" };
export function TaskSection({ areaId, projectId, moduleId }: { areaId: string; projectId?: string; moduleId?: string }) {
  const [tasks, setTasks] = useState<ExplorerTask[]>([]); const [loading, setLoading] = useState(true); const [formTask, setFormTask] = useState<ExplorerTask | "new" | null>(null); const [discardTask, setDiscardTask] = useState<ExplorerTask | null>(null); const [refresh, setRefresh] = useState(0);
  useEffect(() => { let active = true; const params = new URLSearchParams({ areaId, direct: "true" }); if (projectId) params.set("projectId", projectId); if (moduleId) params.set("moduleId", moduleId); fetch(`/api/tasks?${params}`, { cache: "no-store" }).then((response) => { if (!response.ok) throw new Error(); return response.json(); }).then((data) => { if (active) setTasks(data); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [areaId, projectId, moduleId, refresh]);
  const mutate = () => setRefresh((value) => value + 1);
  async function complete(task: ExplorerTask) { await fetch(`/api/tasks/${task.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: "completed" }) }); mutate(); }
  async function discard() { if (!discardTask) return; await fetch(`/api/tasks/${discardTask.id}`, { method: "DELETE" }); setDiscardTask(null); mutate(); }
  const active = tasks.filter((task) => !["completed", "discarded"].includes(task.status)).length; const progress = tasks.filter((task) => task.status === "in_progress").length; const completed = tasks.filter((task) => task.status === "completed").length;
  const direct = projectId && !moduleId ? tasks.filter((task) => !task.moduleId) : tasks; const fromModules = projectId && !moduleId ? tasks.filter((task) => task.moduleId) : [];
  const empty = moduleId ? "No hay tareas en este módulo." : projectId ? "Todavía no hay tareas directas en este proyecto." : "Todavía no hay tareas directas en esta área.";
  return <section className="border-b border-slate-200 py-6"><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Tareas</h2><p className="mt-1 text-xs text-slate-500">{active} activas · {progress} en progreso · {completed} completadas</p></div><Button size="sm" onClick={() => setFormTask("new")}><Plus className="size-4" />Crear tarea</Button></div>{loading ? <p className="py-5 text-sm text-slate-400">Cargando tareas…</p> : tasks.length === 0 ? <div className="rounded-lg border border-dashed border-slate-300 px-4 py-7 text-center text-sm text-slate-500">{empty}</div> : <div className="space-y-5"><TaskList title={projectId && !moduleId ? "Tareas directas del proyecto" : undefined} tasks={direct} showPath={!moduleId} onEdit={setFormTask} onComplete={complete} onDiscard={setDiscardTask} />{fromModules.length > 0 && <TaskList title="Tareas de módulos" tasks={fromModules} showPath onEdit={setFormTask} onComplete={complete} onDiscard={setDiscardTask} />}</div>}
    {formTask && <TaskFormModal key={formTask === "new" ? "new" : formTask.id} open onOpenChange={(open) => !open && setFormTask(null)} task={formTask === "new" ? undefined : formTask} areaId={areaId} projectId={projectId} moduleId={moduleId} onSaved={mutate} />}
    <AlertDialog open={!!discardTask} onOpenChange={(open) => !open && setDiscardTask(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>¿Descartar esta tarea?</AlertDialogTitle><AlertDialogDescription>La tarea dejará de aparecer en las vistas activas, pero no se eliminará definitivamente.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={discard}>Descartar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </section>;
}
function TaskList({ title, tasks, showPath, onEdit, onComplete, onDiscard }: { title?: string; tasks: ExplorerTask[]; showPath: boolean; onEdit: (task: ExplorerTask) => void; onComplete: (task: ExplorerTask) => void; onDiscard: (task: ExplorerTask) => void }) { if (!tasks.length) return null; return <div>{title && <h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-400">{title}</h3>}<div className="divide-y divide-slate-200 rounded-lg border border-slate-200">{tasks.map((task) => <div key={task.id} className="flex items-start gap-3 px-3 py-3"><button aria-label={`Completar ${task.title}`} disabled={task.status === "completed"} onClick={() => onComplete(task)} className={`mt-0.5 grid size-5 shrink-0 place-items-center rounded border ${task.status === "completed" ? "border-emerald-600 bg-emerald-600 text-white" : "border-slate-300 hover:border-slate-500"}`}>{task.status === "completed" && <Check className="size-3" />}</button><div className="min-w-0 flex-1"><p className={`text-sm font-medium ${task.status === "completed" ? "text-slate-400 line-through" : "text-slate-900"}`}>{task.title}</p>{showPath && <p className="mt-1 truncate text-xs text-slate-400">{[task.area.name, task.project?.name, task.module?.name].filter(Boolean).join(" / ")}</p>}<div className="mt-2 flex flex-wrap items-center gap-2"><Badge variant="outline" className="text-[10px]">{priorityLabels[task.priority]}</Badge><Badge variant="outline" className="text-[10px]">{statusLabels[task.status]}</Badge>{task.dueDate && <span className="flex items-center gap-1 text-[11px] text-slate-500"><Clock3 className="size-3" />{new Intl.DateTimeFormat("es-AR").format(new Date(task.dueDate))}</span>}</div></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`Acciones de ${task.title}`}><MoreHorizontal className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={() => onEdit(task)}><Pencil className="size-4" />Editar</DropdownMenuItem>{task.status !== "completed" && <DropdownMenuItem onClick={() => onComplete(task)}><Check className="size-4" />Completar</DropdownMenuItem>}<DropdownMenuItem className="text-red-700" onClick={() => onDiscard(task)}><Trash2 className="size-4" />Descartar</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}</div></div>; }
