"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import type { ExplorerResource, ResourceStatus, ResourceType } from "@/lib/resource-types";
const types: [ResourceType, string][] = [["domain","Dominio"],["hosting","Hosting"],["database","Base de datos"],["repository","Repositorio"],["api","API"],["design_file","Archivo de diseño"],["provider","Proveedor"],["tool","Herramienta"],["account","Cuenta"],["cloud_service","Servicio cloud"],["payment_gateway","Pasarela de pago"],["analytics","Analítica"],["backup","Backup"],["server","Servidor"],["other","Otro"]];
const statuses: [ResourceStatus, string][] = [["active","Activo"],["inactive","Inactivo"],["pending","Pendiente"],["expired","Expirado"],["cancelled","Cancelado"]];
export function ResourceFormModal({ open, onOpenChange, resource, areaId, projectId, moduleId, onSaved }: { open: boolean; onOpenChange: (open: boolean) => void; resource?: ExplorerResource; areaId: string; projectId?: string; moduleId?: string; onSaved: () => void }) {
  const [name,setName]=useState(resource?.name??""); const [type,setType]=useState<ResourceType>(resource?.type??"other"); const [status,setStatus]=useState<ResourceStatus>(resource?.status??"active");
  const [provider,setProvider]=useState(resource?.provider??""); const [url,setUrl]=useState(resource?.url??""); const [renewalDate,setRenewalDate]=useState(resource?.renewalDate?.slice(0,10)??""); const [notes,setNotes]=useState(resource?.notes??"");
  const [hasCredential,setHasCredential]=useState(resource?.credentialProvider==="la_caja"); const [credentialLabel,setCredentialLabel]=useState(resource?.credentialLabel??""); const [credentialReference,setCredentialReference]=useState(resource?.credentialReference??""); const [credentialUsernameHint,setCredentialUsernameHint]=useState(resource?.credentialUsernameHint??"");
  const [saving,setSaving]=useState(false); const [error,setError]=useState("");
  async function save(){setSaving(true);setError("");try{const response=await fetch(`/api/resources${resource?`/${resource.id}`:""}`,{method:resource?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,type,status,provider,url,renewalDate:renewalDate||null,notes,areaId,projectId:projectId??resource?.projectId??null,moduleId:moduleId??resource?.moduleId??null,credentialProvider:hasCredential?"la_caja":null,credentialLabel:hasCredential?credentialLabel:null,credentialReference:hasCredential?credentialReference:null,credentialUsernameHint:hasCredential?credentialUsernameHint:null})});const body=await response.json();if(!response.ok)throw new Error(body.error??"No se pudo guardar el recurso.");onSaved();onOpenChange(false)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo guardar el recurso.")}finally{setSaving(false)}}
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{resource?"Editar recurso":"Crear recurso"}</DialogTitle><DialogDescription>La ubicación jerárquica se asigna automáticamente.</DialogDescription></DialogHeader><div className="space-y-4 py-2">
    <Field label="Nombre"><Input aria-label="Nombre del recurso" value={name} onChange={event=>setName(event.target.value)}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo"><Select value={type} onValueChange={value=>setType(value as ResourceType)}><SelectTrigger aria-label="Tipo de recurso"><SelectValue/></SelectTrigger><SelectContent>{types.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Estado"><Select value={status} onValueChange={value=>setStatus(value as ResourceStatus)}><SelectTrigger aria-label="Estado del recurso"><SelectValue/></SelectTrigger><SelectContent>{statuses.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field></div>
    <Field label="Proveedor"><Input aria-label="Proveedor" value={provider} onChange={event=>setProvider(event.target.value)}/></Field><Field label="URL"><Input aria-label="URL del recurso" placeholder="github.com/organizacion/repositorio" value={url} onChange={event=>setUrl(event.target.value)}/></Field><Field label="Fecha de renovación"><Input aria-label="Fecha de renovación" type="date" value={renewalDate} onChange={event=>setRenewalDate(event.target.value)}/></Field><Field label="Notas"><Textarea aria-label="Notas del recurso" value={notes} onChange={event=>setNotes(event.target.value)} rows={3}/></Field>
    <div className="space-y-4 rounded-lg border border-slate-200 bg-slate-50 p-4"><div className="flex items-center gap-3"><Checkbox id="has-credential" checked={hasCredential} onCheckedChange={value=>setHasCredential(value===true)}/><Label htmlFor="has-credential">Tiene credencial asociada en La Caja</Label></div><p className="text-xs leading-5 text-slate-500">La contraseña, token o clave real no se guarda en Nexo. Cuando la integración esté disponible, este recurso podrá vincularse con La Caja.</p>{hasCredential&&<div className="space-y-4"><Field label="Proveedor de credencial"><Input aria-label="Proveedor de credencial" value="La Caja" disabled/></Field><Field label="Etiqueta de credencial"><Input aria-label="Etiqueta de credencial" value={credentialLabel} onChange={event=>setCredentialLabel(event.target.value)}/></Field><Field label="Referencia de La Caja"><Input aria-label="Referencia de La Caja" placeholder="la-caja://credential/abc123" value={credentialReference} onChange={event=>setCredentialReference(event.target.value)}/></Field><Field label="Usuario visible / pista"><Input aria-label="Usuario visible o pista" value={credentialUsernameHint} onChange={event=>setCredentialUsernameHint(event.target.value)}/></Field></div>}</div>
    {error&&<p role="alert" className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Guardando…":"Guardar"}</Button></DialogFooter></DialogContent></Dialog>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
