"use client";
import { useEffect, useState } from "react";
import { Archive, ExternalLink, MoreHorizontal, Pencil, Plus, ShieldCheck } from "lucide-react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { ResourceFormModal } from "@/components/resources/resource-form-modal";
import type { ExplorerResource, ResourceStatus, ResourceType } from "@/lib/resource-types";
const typeLabels:Record<ResourceType,string>={domain:"Dominio",hosting:"Hosting",database:"Base de datos",repository:"Repositorio",api:"API",design_file:"Archivo de diseño",provider:"Proveedor",tool:"Herramienta",account:"Cuenta",cloud_service:"Servicio cloud",payment_gateway:"Pasarela de pago",analytics:"Analítica",backup:"Backup",server:"Servidor",other:"Otro"};
const statusLabels:Record<ResourceStatus,string>={active:"Activo",inactive:"Inactivo",pending:"Pendiente",expired:"Expirado",cancelled:"Cancelado"};
export function ResourceSection({areaId,projectId,moduleId}:{areaId:string;projectId?:string;moduleId?:string}){
  const [resources,setResources]=useState<ExplorerResource[]>([]);const[loading,setLoading]=useState(true);const[formResource,setFormResource]=useState<ExplorerResource|"new"|null>(null);const[archiveResource,setArchiveResource]=useState<ExplorerResource|null>(null);const[refresh,setRefresh]=useState(0);
  useEffect(()=>{let active=true;const params=new URLSearchParams({areaId});if(projectId)params.set("projectId",projectId);if(moduleId)params.set("moduleId",moduleId);fetch(`/api/resources?${params}`,{cache:"no-store"}).then(response=>{if(!response.ok)throw new Error();return response.json()}).then(data=>{if(active)setResources(data)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[areaId,projectId,moduleId,refresh]);
  const mutate=()=>setRefresh(value=>value+1);async function archive(){if(!archiveResource)return;await fetch(`/api/resources/${archiveResource.id}`,{method:"DELETE"});setArchiveResource(null);mutate()}
  const direct=projectId&&!moduleId?resources.filter(item=>!item.moduleId):resources;const fromModules=projectId&&!moduleId?resources.filter(item=>item.moduleId):[];
  const empty=moduleId?"No hay recursos asociados.":"Todavía no hay recursos en este nivel.";
  return <section className="border-b border-slate-200 py-6"><div className="mb-3 flex items-center justify-between gap-3"><div><h2 className="text-sm font-semibold">Recursos</h2><p className="mt-1 text-xs text-slate-500">{resources.length} recursos visibles</p></div><Button size="sm" onClick={()=>setFormResource("new")}><Plus className="size-4"/>Crear recurso</Button></div>{loading?<p className="py-5 text-sm text-slate-400">Cargando recursos…</p>:resources.length===0?<div className="rounded-lg border border-dashed border-slate-300 px-4 py-7 text-center text-sm text-slate-500">{empty}</div>:<div className="space-y-5"><ResourceList title={projectId&&!moduleId?"Recursos directos del proyecto":undefined} resources={direct} showPath={!moduleId} onEdit={setFormResource} onArchive={setArchiveResource}/>{fromModules.length>0&&<ResourceList title="Recursos de módulos" resources={fromModules} showPath onEdit={setFormResource} onArchive={setArchiveResource}/>}</div>}{formResource&&<ResourceFormModal key={formResource==="new"?"new":formResource.id} open onOpenChange={open=>!open&&setFormResource(null)} resource={formResource==="new"?undefined:formResource} areaId={areaId} projectId={projectId} moduleId={moduleId} onSaved={mutate}/>}<AlertDialog open={!!archiveResource} onOpenChange={open=>!open&&setArchiveResource(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>¿Archivar este recurso?</AlertDialogTitle><AlertDialogDescription>El recurso dejará de aparecer como activo, pero no se eliminará definitivamente.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={archive}>Archivar</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></section>
}
function ResourceList({title,resources,showPath,onEdit,onArchive}:{title?:string;resources:ExplorerResource[];showPath:boolean;onEdit:(item:ExplorerResource)=>void;onArchive:(item:ExplorerResource)=>void}){if(!resources.length)return null;return <div>{title&&<h3 className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-400">{title}</h3>}<div className="divide-y divide-slate-200 rounded-lg border border-slate-200">{resources.map(item=><div key={item.id} className="flex items-start gap-3 px-3 py-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium text-slate-900">{item.name}</p><Badge variant="outline" className="text-[10px]">{typeLabels[item.type]}</Badge><Badge variant="outline" className="text-[10px]">{statusLabels[item.status]}</Badge>{item.credentialProvider==="la_caja"&&<Badge variant="outline" className="gap-1 border-violet-200 bg-violet-50 text-[10px] text-violet-700" title={item.credentialLabel??undefined}><ShieldCheck className="size-3"/>Credencial: La Caja</Badge>}</div>{showPath&&<p className="mt-1 truncate text-xs text-slate-400">{[item.area.name,item.project?.name,item.module?.name].filter(Boolean).join(" / ")}</p>}<div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-slate-500">{item.provider&&<span>{item.provider}</span>}{item.renewalDate&&<Renewal date={item.renewalDate}/>} {item.url&&<a href={item.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 font-medium text-blue-700 hover:underline">Abrir <ExternalLink className="size-3"/></a>}</div></div><DropdownMenu><DropdownMenuTrigger asChild><Button variant="ghost" size="icon" aria-label={`Acciones de ${item.name}`}><MoreHorizontal className="size-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onClick={()=>onEdit(item)}><Pencil className="size-4"/>Editar</DropdownMenuItem><DropdownMenuItem className="text-red-700" onClick={()=>onArchive(item)}><Archive className="size-4"/>Archivar</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>)}</div></div>}
function Renewal({date}:{date:string}){const value=new Date(date);const today=new Date();today.setHours(0,0,0,0);const days=Math.ceil((value.getTime()-today.getTime())/86400000);const label=days<0?"Vencida":days<=30?"Próxima":"Renueva";const color=days<0?"text-red-700":days<=30?"text-amber-700":"text-slate-500";return <span className={color}>{label} {new Intl.DateTimeFormat("es-AR").format(value)}</span>}
