"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { emptyBoardData, type BoardStatus, type BoardType, type VisualBoard } from "@/lib/board-types";
const types: [BoardType,string][]=[["whiteboard","Pizarra"],["flowchart","Diagrama de flujo"],["architecture","Arquitectura"],["process","Proceso"],["mindmap","Mapa mental"],["notes","Notas visuales"],["other","Otro"]];
export function BoardFormModal({open,onOpenChange,board,areaId,projectId,moduleId,onSaved}:{open:boolean;onOpenChange:(open:boolean)=>void;board?:VisualBoard;areaId:string;projectId?:string;moduleId?:string;onSaved:(board:VisualBoard)=>void}){
  const[title,setTitle]=useState(board?.title??"");const[description,setDescription]=useState(board?.description??"");const[type,setType]=useState<BoardType>(board?.type??"whiteboard");const[status,setStatus]=useState<BoardStatus>(board?.status??"draft");const[saving,setSaving]=useState(false);const[error,setError]=useState("");
  async function save(){setSaving(true);setError("");try{const response=await fetch(`/api/boards${board?`/${board.id}`:""}`,{method:board?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title,description,type,status,areaId,projectId:projectId??board?.projectId??null,moduleId:moduleId??board?.moduleId??null,...(!board?{data:emptyBoardData()}: {})})});const body=await response.json();if(!response.ok)throw new Error(body.error??"No se pudo guardar la pizarra.");onSaved(body);onOpenChange(false)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo guardar la pizarra.")}finally{setSaving(false)}}
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><DialogTitle>{board?"Editar pizarra":"Crear pizarra"}</DialogTitle><DialogDescription>Documentación visual asociada a la estructura de Nexo.</DialogDescription></DialogHeader><div className="space-y-4 py-2"><Field label="Título"><Input aria-label="Título de la pizarra" value={title} onChange={event=>setTitle(event.target.value)}/></Field><Field label="Descripción"><Textarea aria-label="Descripción de la pizarra" value={description} onChange={event=>setDescription(event.target.value)} rows={3}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Tipo"><Select value={type} onValueChange={value=>setType(value as BoardType)}><SelectTrigger aria-label="Tipo de pizarra"><SelectValue/></SelectTrigger><SelectContent>{types.map(([value,label])=><SelectItem key={value} value={value}>{label}</SelectItem>)}</SelectContent></Select></Field><Field label="Estado"><Select value={status} onValueChange={value=>setStatus(value as BoardStatus)}><SelectTrigger aria-label="Estado de pizarra"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="draft">Borrador</SelectItem><SelectItem value="active">Activo</SelectItem><SelectItem value="archived">Archivado</SelectItem></SelectContent></Select></Field></div><p className="rounded-md bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-800">Esta pizarra es para documentación visual. No guardes contraseñas, tokens ni secretos. Para eso se usará La Caja.</p>{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}</div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button onClick={save} disabled={saving}>{saving?"Guardando…":"Guardar"}</Button></DialogFooter></DialogContent></Dialog>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
