"use client";
import { useState } from "react";
import type { BoardData, BoardEdge, BoardNode } from "@/lib/board-types";
export type BoardMode = "select" | "connect" | "delete";
export function BoardCanvas({data,onChange,mode,selectedNodeId,onSelectNode,connectFrom,onConnect,fullscreen=false}:{data:BoardData;onChange:(data:BoardData)=>void;mode:BoardMode;selectedNodeId:string|null;onSelectNode:(id:string|null)=>void;connectFrom:string|null;onConnect:(id:string)=>void;fullscreen?:boolean}){
  const[drag,setDrag]=useState<{id:string;offsetX:number;offsetY:number}|null>(null);
  const updateNode=(id:string,patch:Partial<BoardNode>)=>onChange({...data,nodes:data.nodes.map(node=>node.id===id?{...node,...patch}:node)});
  const removeNode=(id:string)=>onChange({...data,nodes:data.nodes.filter(node=>node.id!==id),edges:data.edges.filter(edge=>edge.fromNodeId!==id&&edge.toNodeId!==id)});
  const nodeClick=(id:string)=>{if(mode==="connect")onConnect(id);else if(mode==="delete")removeNode(id);else onSelectNode(id)};
  function startDrag(event:React.PointerEvent,node:BoardNode){if(mode!=="select"||event.button!==0)return;const rect=(event.currentTarget as HTMLElement).closest('[aria-label="Canvas de pizarra"]')!.getBoundingClientRect();setDrag({id:node.id,offsetX:event.clientX-rect.left-node.x,offsetY:event.clientY-rect.top-node.y});onSelectNode(node.id);event.currentTarget.setPointerCapture(event.pointerId)}
  function move(event:React.PointerEvent<HTMLDivElement>){if(!drag)return;const rect=event.currentTarget.getBoundingClientRect();updateNode(drag.id,{x:Math.max(0,event.clientX-rect.left-drag.offsetX),y:Math.max(0,event.clientY-rect.top-drag.offsetY)})}
  return <div aria-label="Canvas de pizarra" className={`relative min-w-[900px] overflow-hidden bg-[radial-gradient(#cbd5e1_1px,transparent_1px)] [background-size:20px_20px] ${fullscreen?"h-[calc(100vh-5.5rem)]":"h-[620px]"}`} onPointerMove={move} onPointerUp={()=>setDrag(null)} onPointerLeave={()=>setDrag(null)} onClick={event=>{if(event.target===event.currentTarget)onSelectNode(null)}}>
    <svg className="pointer-events-none absolute inset-0 size-full"><defs><marker id="arrow" markerWidth="10" markerHeight="10" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#64748b"/></marker></defs>{data.edges.map(edge=><EdgeLine key={edge.id} edge={edge} nodes={data.nodes} onDelete={()=>mode==="delete"&&onChange({...data,edges:data.edges.filter(item=>item.id!==edge.id)})}/>)}</svg>
    {data.nodes.map(node=><Node key={node.id} node={node} selected={selectedNodeId===node.id} connecting={connectFrom===node.id} onClick={()=>nodeClick(node.id)} onMoveStart={startDrag} onText={(text)=>updateNode(node.id,{text})}/>)}
  </div>
}
function EdgeLine({edge,nodes,onDelete}:{edge:BoardEdge;nodes:BoardNode[];onDelete:()=>void}){const from=nodes.find(node=>node.id===edge.fromNodeId);const to=nodes.find(node=>node.id===edge.toNodeId);if(!from||!to)return null;const x1=from.x+from.width/2,y1=from.y+from.height/2,x2=to.x+to.width/2,y2=to.y+to.height/2;return <g className="pointer-events-auto cursor-pointer" onClick={event=>{event.stopPropagation();onDelete()}}><line x1={x1} y1={y1} x2={x2} y2={y2} stroke="transparent" strokeWidth="14"/><line x1={x1} y1={y1} x2={x2} y2={y2} stroke="#64748b" strokeWidth="2" markerEnd={edge.type==="arrow"?"url(#arrow)":undefined}/></g>}
function Node({node,selected,connecting,onClick,onMoveStart,onText}:{node:BoardNode;selected:boolean;connecting:boolean;onClick:()=>void;onMoveStart:(event:React.PointerEvent,node:BoardNode)=>void;onText:(text:string)=>void}){const border=selected?"border-slate-950 ring-2 ring-slate-300":connecting?"border-blue-600 ring-2 ring-blue-200":"border-slate-300";const shape=node.type==="text"?"border-transparent shadow-none":node.shape==="ellipse"?"rounded-full":node.shape==="diamond"?"rotate-45":node.shape==="sticky"?"rounded-sm border-amber-200 shadow-md":"rounded-lg";return <div className={`absolute border-2 shadow-sm ${border} ${shape}`} style={{left:node.x,top:node.y,width:node.width,height:node.height,backgroundColor:node.color}} onClick={event=>{event.stopPropagation();onClick()}}><button aria-label={`Mover nodo ${node.id}`} className={`absolute right-1 top-1 z-10 cursor-move rounded px-1 text-xs text-slate-400 hover:bg-black/5 ${node.shape==="diamond"?"-rotate-45":""}`} onPointerDown={event=>onMoveStart(event,node)}>⠿</button><textarea aria-label={`Texto de nodo ${node.id}`} value={node.text} onPointerDown={event=>event.stopPropagation()} onClick={event=>{event.stopPropagation();onClick()}} onChange={event=>onText(event.target.value)} className={`size-full resize-none bg-transparent p-3 pt-7 text-sm font-medium outline-none ${node.shape==="diamond"?"-rotate-45 text-center":node.type==="text"?"pt-3 text-base font-normal":" "}`}/></div>}
